<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.cache.warm_internal' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'contao'.\DIRECTORY_SEPARATOR.'core-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Cache'.\DIRECTORY_SEPARATOR.'ContaoCacheWarmer.php';

return $this->services['contao.cache.warm_internal'] = new \Contao\CoreBundle\Cache\ContaoCacheWarmer(($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($this->services['contao.resource_finder'] ?? $this->getContao_ResourceFinderService()), ($this->services['contao.resource_locator'] ?? $this->load('getContao_ResourceLocatorService.php')), \dirname(__DIR__, 4), ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['Contao\\CoreBundle\\Intl\\Locales'] ?? $this->getLocalesService()));
